spring:
    datasource:
        url: jdbc:mysql://localhost:3306/data_db?useSSL=false&serverTimezone=Bangkok
        username: root
        password: 03042001
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL8Dialect